name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:

  build:

    runs-on: self-hosted
    steps:    
      - uses: actions/checkout@v4
      
      - name: Login to DockerHUB 
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
          
      - name: BookApp Build, tag, and push image to DockerHUB  
        env:
          IMAGE_NAME: book-app
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG ./app
          docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG

      - name: Update GitOps Values
        env:
            IMAGE_TAG: ${{ github.sha }}
        run: |
            sed -i "" "s/tag: v1/tag: $IMAGE_TAG/" gitops/chart/values.yaml

      - name: Set TIMESTAMP env variable
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Package Helm Chart
        run: |
          helm package gitops/chart --destination . --app-version $TIMESTAMP --version $TIMESTAMP

      - name: Rename Chart Package
        run: |
          CHART_NAME="chart-${TIMESTAMP}.tgz"
          mv *.tgz $CHART_NAME

      - name: Upload Chart to Nexus
        run: |
          CHART_NAME="chart-${TIMESTAMP}.tgz"
          curl -v -F file=@$CHART_NAME -u $NEXUS_USERNAME:$NEXUS_PASSWORD "http://$NEXUS_URL/service/rest/v1/components?repository==helm-hosted"
      
    
    
