name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:

  build:

    runs-on: self-hosted
    steps:    
      - uses: actions/checkout@v4
      
      - name: Login to DockerHUB 
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
          
      - name: BookApp Build, tag, and push image to DockerHUB  
        env:
          IMAGE_NAME: book-app
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          pwd
          docker build -t $IMAGE_NAME:$IMAGE_TAG ./app
          docker tag $IMAGE_NAME $DOCKER_USERNAME/$IMAGE_NAME
          docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
    
    
